### ISSUE TITLE
Get all show and movies from specific year

### ISSUE THREAD

**Issue by AlexandrosPa** [oxplot/imdb2json#8]
Hello, First of all I would like to thank you for this amazing script. I wanted to ask if there is any way to convert all movies and show from 2010 and later.

**Comment by oxplot** [comment]
no, but given the output is JSON, you can convert all and trivially filter
it using jq

**Comment by AlexandrosPa** [comment]
can you give me some tips on how can i do that?

**Comment by oxplot** [comment]
Sure.

You need `movies.list.gz` to get the year of the movie/episode/show. Download and covert it:

```
./imdb2json.py convert title movies.list.gz > movies.json
```

You can convert other files at the same time or merge them later (see Readme) but for simplicity's sake, we're just going to stick with this one file.

Now you can use `jq` command line tool to filter out all records but those from 2010 onwards:

```
jq 'select(.year[0] >= 2010)' movies.json
```

or only the movies in 2016:

```
jq 'select(.kind == "movie" and .year[0] == 2016)' movies.json
```
